server:
  port: ${PORT:8080}

spring:
  application:
    name: warehouse-api
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
    username: postgres.npelqbzkvslfgsapmurd
    password: dimasfathulyaqin
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true